name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [^10, ^11, ^12]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        exclude:
          - php: 8.1
            laravel: ^12
          - php: 8.1
            laravel: ^11
          - php: 8.4
            laravel: ^10

    name: PHP${{ matrix.php }} Laravel${{ matrix.laravel }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest --with-all-dependencies

      - name: Execute Unit Tests
        run: composer test
